trigger:
  branches:
    include:
    - main
    - Test-checkov
    - testing01
pr:
- main
variables: 
  workingDirectory: '$(System.DefaultWorkingDirectory)/examples/basic'
stages:
- stage: TerraformJobDev_Init_Plan
  displayName: Terraform Module - Init - Plan
  jobs:
    - job: TerraformJobDEV
      displayName: Terraform - CI Job - DEV
      pool: pipelinetest
      steps:
        # - task: Bash@3
        #   displayName: Install pip
        #   inputs:
        #    targetType: 'inline'
        #    script: ' sudo apt install python2 -y '     
                  
        - task: Bash@3
          displayName: Install checkov
          inputs:
           targetType: 'inline'
           script: 'pip install checkov '
        
        - task: Bash@3
          displayName: Checkov source code scan  
          inputs:
            targetType: 'inline'
            workingDirectory: ${{ variables.workingDirectory }}
            script: 'checkov -d . '
          # continueOnError: true
           
        # - task: PublishTestResults@2
        #   inputs:
        #     testResultsFormat: 'JUnit'
        #     searchFolder: '$(System.DefaultWorkingDirectory)'
        #     testResultsFiles: 'scan-result.xml'
        #     mergeTestResults: false
        #     testRunTitle: Checkov Dev workspace plan scan
        #     failTaskOnFailedTests: false
        #     publishRunAttachments: true
        #   displayName: Publish Test Resul 
