trigger:
  branches:
    include:
    - main
    

pr: none


stages:
- stage: TerraformJobDev_Init_Plan
  displayName: Terraform Module - Init - Plan
  jobs:
    - job: TerraformJobDEV
      displayName: Terraform - CI Job - DEV
      pool:
        vmImage: ubuntu-latest
      steps:
        - script: |
                sudo apt install unzip
                sudo apt install azure-cli -y
                echo 'System.DefaultWorkingDirectory'
                ls
          name: setup_environment
          displayName: 'Setup TF Environment'

        - task: TerraformInstaller@0
          displayName: install terraform
          inputs:
            terraformVersion: latest

        - task: TerraformInstaller@0
          displayName: 'Terraform init'
          inputs:
            command: 'init'
            workingDirectory: $(System.DefaultWorkingDirectory)
            backendType: 'selfConfigured'
        - task: Bash@3
          displayName: Install pip
          inputs:
           targetType: 'inline'
           script: ' sudo apt install python2		-y '     
                  
        - task: Bash@3
          displayName: Install checkov
          inputs:
           targetType: 'inline'
           script: 'pip install checkov '
        - task: Bash@3
          displayName: Checkov source code scan  
          inputs:
            targetType: 'inline'
            workingDirectory: $(System.DefaultWorkingDirectory)
            script: 'ls'           
        - task: Bash@3
          displayName: Checkov source code scan  
          inputs:
            targetType: 'inline'
            workingDirectory: $(System.DefaultWorkingDirectory)
            script: 'checkov -d . -o junitxml > scan-result.xml'
          continueOnError: true